# SQL Debugging Image
# This image allows to ssh into container and run MS SQL queries using preinstalled sqlcmd
# 1) SSH into container
#   $ docker run -d -P --name test_sshd evision.evenintegration:latest
#   $ docker port test_sshd 22
#   $ ssh root@192.168.1.2 -p 32768
# 2) Run SQL command
#   /opt/mssql-tools/bin/sqlcmd -S 192.168.33.49 -U sa -P Test@123 -q "select @@version"

FROM fabiang/sqlcmd 
#fabiang/sqlcmd is 'ubuntu:16.04' with installed 'sqlcmd'

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:THEPASSWORDYOUCREATED' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
ENTRYPOINT []
CMD ["/usr/sbin/sshd", "-D"]